CXX=g++
CXXFLAGS:=-fPIC -g -ggdb -I$(DIR)/include

all:
	@echo "[II]\tCompiling level "$(LEVEL)
	@for file in *.cpp; do echo "[CXX]\t"$$file && g++ $(CXXFLAGS) $$file -c ; done
	@echo "[LD]\tLinking "$(LEVEL)
	@g++ -rdynamic -ldl ../shared.o *.o -o $(DIR)/lib/$(LEVEL).so -g -ggdb -shared -Wl,-soname,$(LEVEL)

